version: '3.9'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - node1:node1
      - node2:node2
    depends_on:
      - node1
      - node2
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - app-network
    volumes:
      - ./certs:/etc/nginx/certs

  node1:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - ./server/public/uploads:/usr/src/app/public/uploads
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=node1
    depends_on:
      - mongo
    networks:
      - app-network

  node2:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - ./server/public/uploads:/usr/src/app/public/uploads
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=node2
    depends_on:
      - mongo
    networks:
      - app-network

  apinode1:
    build:
      context: ./dbserver
      dockerfile: dbDockerfile
    volumes:
      - ./dbserver:/usr/src/app
      - ./server/models:/usr/src/app/models
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=apinode1
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  apinode2:
    build:
      context: ./dbserver
      dockerfile: dbDockerfile
    volumes:
      - ./dbserver:/usr/src/app
      - ./server/models:/usr/src/app/models
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=apinode2
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  apinode3:
    build:
      context: ./dbserver
      dockerfile: dbDockerfile
    volumes:
      - ./dbserver:/usr/src/app
      - ./server/models:/usr/src/app/models
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=apinode3
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  mongo:
    image: mongo:4.4.6
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.10.14-management-alpine
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
