version: '3.9'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - app-network
    volumes:
      - ./certs:/etc/nginx/certs

  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - ./server/public/uploads:/usr/src/app/public/uploads
      - ./server/node_modules:/usr/src/app/node_modules
    environment:
      - INSTANCE=node
      - VIRTUAL_HOST=localhost
      - USE_IP_HASH=1
    depends_on:
      - mongo
    networks:
      - app-network

  oauth_node:
    build:
      context: ./oauth_server
      dockerfile: Dockerfile
    volumes:
      - ./oauth_server:/usr/src/app
      - ./oauth_server/node_modules:/usr/src/app/node_modules
    environment:
      - INSTANCE=oauth_node
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4.6
    networks:
      - app-network

  rabbit:
    image: rabbitmq
    networks:
      - app-network

    
networks:
  app-network:
    driver: bridge
