version: '3.9'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - node1:node1
    depends_on:
      - node1
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - app-network
    volumes:
      - ./certs:/etc/nginx/certs

  node1:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - ./server/public/uploads:/usr/src/app/public/uploads
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=node1
    depends_on:
      - mongo
      - dbnode
    networks:
      - app-network

  dbnode:
    build:
      context: ./dbserver
      dockerfile: dbDockerfile
    volumes:
      - ./dbserver:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - INSTANCE=dbnode
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  mongo:
    image: mongo:4.4.6
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.10.14
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
