name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkup & Setup Node
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: npm installation
        run: npm install
      - name: Run test
        run: npm test
